version: "3.6"

services:
  ftp:
    image: lovelysystems/docker-proftpd:dev
    hostname: localhost
    network_mode: bridge
    environment:
      TZ: "Europe/Vienna"
    volumes:
    - ./sites.conf:/etc/proftpd/conf.d/sites.conf
    # the password for both users is "password"
    - ./proftpd.passwd:/run/secrets/proftpd.passwd
    - ./volumes/data:/data
    ports:
    - "21:21"
    # only open up 100 ports for testing, since on osx the mapping is slow
    - "49000-49100:49000-49100"
